Layout principal do site do Repositório de Materiais
ieeeifpbcg/cb-repositorio-materiais pull request #2
Opened 2020-02-28 17:25 UTC by arthur-mts

O site foi criado em ReactJS usando o template do Gatsby disponibilizado por @henry-ns .

2020-02-29 14:12 UTC, henriquepw requested changes
1 - Quando se usa `styled-components` ou outra lib de `CSS-in-JS` um dos beneficios é não precisar usar `className` para adicionar estilos nas tags.

Por exemplo, em `BoxDisciplina`:

o jsx está assim:

```jsx
  Container type="button" style={{ background: bg }}>
    <p className="nomeDisc">{parseName(disciplina.nome)}</p>
    <p className="cargaHoraria">{disciplina.ch}</p>
    <p className="idDisc">{disciplina.id}</p>
    <p className="preReq">{disciplina.pr}</p>
  </Container>
```

Tu poderiar criar um componente de estilo para acada um desses paragrafos.

por exemplo:

```jsx
  Container type="button" style={{ background: bg }}>
    <Nome>{parseName(disciplina.nome)}</Nome>
    <CargaHoraria>{disciplina.ch}</CargaHoraria>
    <ID>{disciplina.id}</ID>
    <PreRequisito>{disciplina.pr}</PreRequisito>
  </Container>
```

2 - Pense na semântica antes de escrever, usando o mesmo código de cima como exemplo, que tudo é parágrafo, acho que ficaria melhor o nome da disciplina como `h1` e o resto como `span`.

3 - Cuidado com as animações, prefira sempre animar usando `transform` do que mundando a altura e a largura, é mais performático.

4 - Não use estilo inline, crie um componente no arquivo de estilo e use-o.

5 - No mundo de design, o espaço em branco entre componentes ajuda na leitura, deixando mais fácil de entender, no código é da mesma forma, se voce deixa uma linha em branco em cada "bloco" (tipo, essas 2 primeira linhas fazem x coisa é um bloco, esse `for` depois é outro bloco) fica muita mais fácil de entender.

Não bom
```js
useEffect(() => {
    // Cria uma matriz de arrays vazios para separar as diciplinas por semestre
    const newMatriz = Array.from(new Array(semestres), () => []);
    // Iterar sobre a matriz colocando cada disciplina em seu respectivo array
    matriz.forEach(disciplina => {
      const index = Number.parseInt(disciplina.id.charAt(0), 10) - 1;
      if (newMatriz[index]) newMatriz[index].push(disciplina);
    });
    setSemestresArray(newMatriz);
  }, [matriz, semestres]);
```
Bom
```js
useEffect(() => {
    // Cria uma matriz de arrays vazios para separar as diciplinas por semestre
    const newMatriz = Array.from(new Array(semestres), () => []);
    
    // Iterar sobre a matriz colocando cada disciplina em seu respectivo array
    matriz.forEach(disciplina => {
      const index = Number.parseInt(disciplina.id.charAt(0), 10) - 1;
      if (newMatriz[index]) newMatriz[index].push(disciplina);
    });
    
    setSemestresArray(newMatriz);
  }, [matriz, semestres]);
```

Pode parecer besteira no começo, mas, conforme o código vai crescendo, isso vai se tornando cada vez mais útil.

6 - Atualize o arquivo themes.js com as cores corretas e use-o!

7 - Atualize o `footer` de acordo com o design feito

:bulb: dica: o arquivo com o design no `figma` já da várias informações para criar o css, alias, se clicar em algum componente, ele já da todo o css, mas não use ele completo, use mais para saber os espaçamentos.

2020-03-11 22:43 UTC, arthur-mts commented
Modificações feitas!

2020-03-11 23:29 UTC, henry-ns commented
por que removesse o commitizen?

2020-03-13 00:58 UTC, arthur-mts commented
Nem eu sei

2020-03-28 20:03 UTC, merged